# -*- coding: utf-8 -*-

program: DELSYS_main.py
method: random
metric:
    name: Validation Loss
    goal: minimize
parameters:
    LR:
        values: [0.0005, 0.001, 0.005, 0.01, 0.05]
    n_warmup_steps:
        values: [5, 10, 15]
    decay_rate:
        values: [0.985, 0.99, 0.995]
    # model dim
    model_dim:
        values: [16, 32, 64]
    hidden_dim:
        values: [8, 16, 32]
    hidden1_dim:
        values: [32, 64, 128, 256]
    hidden2_dim:
        values: [8, 16, 32, 64]
    n_layer:
        values: [8, 10, 12]
    n_heads:
        values: [8, 16]
    dropout_p:
        values: [0.1]
    # default
    n_patch:
        values: [429]
    n_output:
        values: [1]
    EPOCHS:
        values: [300]
    BATCH_SIZE:
        values: [16]
    TEST_RATIO:
        values: [0.25]
    RANDOM_STATE:
        values: [42]
    prj_name:
        values: ["HD_ViT"]
    log_interval:
        values: [5]